### ISSUE TITLE
Infografía fases de gestión de proyectos 

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Litzy-lopez4#2]
[Infografía de gestión de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Litzy-lopez4/files/12465692/Infografia.de.gestion.de.proyectos.pdf)

**Comment by MLR062998** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
